"""added rules and values fk

Revision ID: 09f17b13ebf8
Revises: 999261081046
Create Date: 2024-05-09 21:02:56.341865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f17b13ebf8'
down_revision: Union[str, None] = '999261081046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('values', 'rule_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_foreign_key(None, 'values', 'rules', ['rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.alter_column('values', 'rule_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
