"""added users-ducrules FK

Revision ID: 176b4b5c8cd4
Revises: 4a57028d14fd
Create Date: 2024-05-14 18:09:55.040937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176b4b5c8cd4'
down_revision: Union[str, None] = '4a57028d14fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docrules', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docrules', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
