"""added users-ducrules FK

Revision ID: 4a57028d14fd
Revises: 96a0d0420560
Create Date: 2024-05-14 18:08:41.093679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a57028d14fd'
down_revision: Union[str, None] = '96a0d0420560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docrules', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_foreign_key(None, 'docrules', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docrules', type_='foreignkey')
    op.alter_column('docrules', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
