"""added rules definition

Revision ID: 6fdec64cd698
Revises: 09f17b13ebf8
Create Date: 2024-05-11 21:50:40.531328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdec64cd698'
down_revision: Union[str, None] = '09f17b13ebf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('definition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'definition')
    # ### end Alembic commands ###
