"""added rules and values

Revision ID: 999261081046
Revises: b1ee4f5e4563
Create Date: 2024-05-09 20:19:47.160503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999261081046'
down_revision: Union[str, None] = 'b1ee4f5e4563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('values',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    op.drop_table('rules')
    # ### end Alembic commands ###
