"""added queue done

Revision ID: b1ee4f5e4563
Revises: c815a3e1df5b
Create Date: 2024-04-06 21:35:21.187297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ee4f5e4563'
down_revision: Union[str, None] = 'c815a3e1df5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'done')
    # ### end Alembic commands ###
