"""added queue created_at

Revision ID: c815a3e1df5b
Revises: f631df23498f
Create Date: 2024-04-06 21:27:50.428686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c815a3e1df5b'
down_revision: Union[str, None] = 'f631df23498f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('created_at', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'created_at')
    # ### end Alembic commands ###
