"""added user docRule cascade delete

Revision ID: ea7d7858a621
Revises: 8568245f42ab
Create Date: 2024-05-23 11:11:23.093855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7d7858a621'
down_revision: Union[str, None] = '8568245f42ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('docrules_user_id_fkey', 'docrules', type_='foreignkey')
    op.create_foreign_key(None, 'docrules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docrules', type_='foreignkey')
    op.create_foreign_key('docrules_user_id_fkey', 'docrules', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
