"""added queue table

Revision ID: f631df23498f
Revises: e5eba579dd02
Create Date: 2024-04-06 20:45:55.527706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f631df23498f'
down_revision: Union[str, None] = 'e5eba579dd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('doc_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type_id', sa.BIGINT(), nullable=False),
    sa.Column('fix', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['docrules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    # ### end Alembic commands ###
